'packages:biome-config':
  - packages/biome-config/*
  - packages/biome-config/**/*

'packages:eslint-config':
  - packages/eslint-config/*
  - packages/eslint-config/**/*

'packages:prettier-config':
  - packages/prettier-config/*
  - packages/prettier-config/**/*

'packages:ts-config':
  - packages/ts-config/*
  - packages/ts-config/**/*

'packages:utilities':
  - packages/utilities/*
  - packages/utilities/**/*
