- name: backlog
  color: '16774c'
- name: bug:confirmed
  color: 'fc1423'
- name: bug:unverified
  color: 'f9d0c4'
- name: chore
  color: 'ffffff'
- name: ci
  color: '0075ca'
- name: dependencies
  color: '276bd1'
- name: discussion
  color: 'b6b1f9'
- name: documentation
  color: '0075ca'
- name: duplicate
  color: 'bac4c2'
- name: feature
  color: 'ffff00'
- name: has PR
  color: '4b1f8e'
- name: help wanted
  color: '008672'
- name: in progress
  color: 'ffccd7'
- name: in review
  color: 'aed5fc'
- name: invalid
  color: 'e4e669'
- name: need repro
  color: 'c66037'
- name: needs rebase & merge
  color: '24853c'
- name: packages:biome-config
  color: 'fbca04'
- name: packages:eslint-config
  color: 'fbca04'
- name: packages:prettier-config
  color: 'fbca04'
- name: packages:ts-config
  color: 'fbca04'
- name: packages:utilities
  color: 'fbca04'
- name: performance
  color: '80c042'
- name: priority:critical
  color: 'b60205'
- name: priority:high
  color: 'fc1423'
- name: priority:low
  color: 'bac60e'
- name: priority:lowest
  color: '5a7532'
- name: question
  color: 'd876e3'
- name: refactor
  color: '1d637f'
- name: regression
  color: 'ea8785'
- name: tests
  color: 'f06dff'
- name: typings
  color: '80c042'
- name: wontfix
  color: 'ffffff'
- name: stale
  color: 'ead18c'
