name: Label sync
on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  label-sync:
    name: Label sync
    runs-on: ubuntu-latest
    if: github.repository_owner == 'dareharu'
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Label sync
        uses: crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1a9c5bb28922f3e1b # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
