name: Lock Ancient Issues
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 365
          issue-lock-reason: resolved
          process-only: issues
